### ISSUE TITLE
гавняный код неработает

### ISSUE THREAD

**Issue by PopLocker714** [367300/file-api-server#3]
код ноптемезирован, кароче код гавно удаляй а катара мая 😀😋

**Comment by 367300** [comment]
Гавнянный код работает как надо по тз, а катара моя

**Comment by PopLocker714** [comment]
ПППППППППППППААААААААААААААААШООООООООООООООООООООЛТЫЫЫ

**Comment by PopLocker714** [comment]
КОД Г

**Comment by 367300** [comment]
Катюшке привет передавай

**Comment by PopLocker714** [comment]
Почему все в одном файле?🤮

**Comment by 367300** [comment]
Со временем раскидаю по хендлерам

**Comment by PopLocker714** [comment]
ясно все, как раскидаешь закрой

**Comment by PopLocker714** [comment]
ладно все чтобы в следующем коммите закрыл
